import registry from "./languages.json";

export interface LanguageMeta {
  /** BCP-47-ish code matching the locale filename (`<code>.json`) and gtx target. */
  code: string;
  /** English name of the language. */
  name: string;
  /** Endonym — the language's own name, shown in the switcher. */
  nativeName: string;
}

/**
 * Full language registry (192 entries). `en` + `pt-BR` are hand-authored; every
 * other locale is machine-generated by agents/i18n/translate.py. Mirrors the
 * agent's canonical langs.json so adding a language stays a one-row change.
 */
export const LANGUAGES: readonly LanguageMeta[] = (registry as { languages: LanguageMeta[] }).languages;

/**
 * Right-to-left locales — the UI sets `document.documentElement.dir = "rtl"`
 * for these. Only scripts actually written RTL are listed (Kurmanji Kurdish
 * `ku` is Latin-script, so it stays LTR; Sorani `ckb` is RTL).
 */
export const RTL_LANGS: ReadonlySet<string> = new Set([
  "ar", // Arabic
  "fa", // Persian
  "he", // Hebrew
  "ur", // Urdu
  "ps", // Pashto
  "sd", // Sindhi
  "ug", // Uyghur
  "ckb", // Kurdish (Sorani)
  "dv", // Dhivehi
  "yi", // Yiddish
  "ms-Arab", // Malay (Jawi)
  "pa-Arab", // Punjabi (Shahmukhi)
]);
